OUTPUT_ROOT: matchtrack_15_ch_6w_fix_posnorm_bugs_norefidx_layer6_iterative
DIST_BACKEND: 'nccl'
WORKERS: 0
DEVICE: cuda
SEED: 42
DATASET:
  FILE: match_ch
  NAME: MatchCHDataset
  ROOT: '/mnt/lustre/chenmingfei/code/MOT_DeformableSet/data/mot_pkl/'
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  IMG_NUM_PER_GPU: 1
  NUM_CLASSES: 2 # id 加 1
  MAX_SIZE: 1088 #1333
  SCALES: [608,]
  PREFIX: '/mnt/lustre/chenmingfei/data/MOT_data/'
MODEL:
  FILE: deformable_matchtrack_ch
  NAME: DeformableMatchTrack
  # RESUME_PATH: 'data/r50_deformable_detr-checkpoint.pth'
  RESUME_PATH: 'data/r50_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage-checkpoint.pth'
  # RESUME_PATH: 'output/matchtrack_15_ch_6w_fix_posnorm_bugs_norefidx_DeformableMatchTrack_epoch005_checkpoint.pth'
  # RESUME_PATH: 'output/matchtrack_15_ch_6w_fix_posnorm_bugs_norefidx_iterative_DeformableMatchTrack_epoch004_checkpoint.pth'
  # RESUME_PATH: 'output/matchtrack_15_ch_6w_fix_posnorm_bugs_norefidx_layer1_DeformableMatchTrack_epoch005_checkpoint.pth'
  # RESUME_PATH: 'output/matchtrack_15_ch_6w_fix_posnorm_bugs_norefidx_layer6_DeformableMatchTrack_epoch004_checkpoint.pth'
BACKBONE:
  NAME: resnet50
  DIALATION: False
DEFORMABLE:
  WITH_BOX_REFINE: True
  TWO_STAGE: True
TRANSFORMER:
  POSITION_EMBEDDING: sine # choices=('sine', 'learned')
  NUM_FEATURE_LEVELS: 4 
  HIDDEN_DIM: 256
  ENC_LAYERS: 6
  DEC_LAYERS: 6
  DIM_FEEDFORWARD: 1024
  DROPOUT: 0.1
  NHEADS: 8
  NUM_QUERIES: 300
  DEC_N_POINTS: 4
  ENC_N_POINTS: 4
  PRE_NORM: False
MATCHER:
  COST_CLASS: 1
  COST_BBOX: 5
  COST_GIOU: 2
LOSS: 
  AUX_LOSS: True
  DICE_LOSS_COEF: 1
  ID_LOSS_COEF: 0.5
  OFFSET_LOSS_COEF: 5
  CLS_LOSS_COEF: 2
  BBOX_LOSS_COEF: 5
  GIOU_LOSS_COEF: 2
  FOCAL_ALPHA: 0.25
TRAINER:
  FILE: det_trainer
  NAME: TrackTrainer
TRAIN:
  LR: 0.0001
  LR_BACKBONE: 0.00001
  LR_BACKBONE_NAMES: ["backbone.0"]
  LR_PROJ_MULT: 0.1
  LR_PROJ_NAMES: ['reference_points', 'sampling_offsets']
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LR_DROP: 22 #40
  MAX_EPOCH: 30 #50
  PRINT_FREQ: 20
  SAVE_INTERVAL: 5 #5
  SAVE_EVERY_CHECKPOINT: True
  VAL_WHEN_TRAIN: False
  CLIP_MAX_NORM: 0.1
  RESUME: False
