OUTPUT_ROOT: mot_base
DIST_BACKEND: 'nccl'
WORKERS: 4
DEVICE: cuda
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  FILE: mot
  NAME: MOTDataset
  ROOT: 'data/MOT17'
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  IMG_NUM_PER_GPU: 2
  OBJ_NUM_CLASSES: 1 # id 不减 1
  MAX_SIZE: 1333 #1333
  SCALES: [608, 640, 672, 704, 736, 768, 800]
MODEL:
  FILE: mot_transformer_base
  NAME: MOT_Transformer
  RESUME_PATH: 'data/crowd_r50_300.pth'
BACKBONE:
  NAME: resnet50
  DIALATION: False
TRANSFORMER:
  POSITION_EMBEDDING: sine # choices=('sine', 'learned')
  HIDDEN_DIM: 256
  ENC_LAYERS: 6
  DEC_LAYERS: 6
  DIM_FEEDFORWARD: 2048
  DROPOUT: 0.1
  NHEADS: 8
  NUM_QUERIES: 150
  PRE_NORM: False
MATCHER:
  COST_CLASS: 1
  COST_BBOX: 5
  COST_GIOU: 2
LOSS: 
  AUX_LOSS: True
  DICE_LOSS_COEF: 1
  DET_CLS_COEF: [1, 1]
  REL_CLS_COEF: 1
  BBOX_LOSS_COEF: [5, 5]
  GIOU_LOSS_COEF: [2, 2]
  EOS_COEF: 0.1
TRAINER:
  FILE: mot_trainer
  NAME: MOTTrainer
TRAIN:
  LR: 0.0001
  LR_BACKBONE: 0.00001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LR_DROP: 60
  MAX_EPOCH: 100
  PRINT_FREQ: 20
  SAVE_INTERVAL: 5
  SAVE_EVERY_CHECKPOINT: True
  VAL_WHEN_TRAIN: False
  CLIP_MAX_NORM: 0.1
  RESUME: False
